# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97ef24eda47e5d2c5456a40a4a4537ab0e7935d0a391de1835213e189a6690a99f59f8ca1a6cb4a4cbd5e6038d7c6812bc2c0233719d47552171655755cae10a

test:
  secret_key_base: 694d1e32f4353e538a8065ab7a9930abe14ced75cc741b76b59b04feee03ba861cba12ec0df00cd411396b47446bcddad024bd8c6e8716da9a8278528a41acd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
